# Generated by Django 5.0.1 on 2024-03-23 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_product_color_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.brand",
            ),
        ),
    ]
