# Generated by Django 5.0.1 on 2024-02-26 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="decriptin",
            new_name="description",
        ),
    ]
