# Generated by Django 5.0.1 on 2024-03-31 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_alter_productimage_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={"verbose_name_plural": "Sizes"},
        ),
    ]
