# Generated by Django 5.0.1 on 2024-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
