# Generated by Django 5.0.1 on 2024-03-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
        ("product", "0003_rename_category_product_category_and_more"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="paid_ammount",
            new_name="paid_amount",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="vnedor_paid",
            new_name="vendor_paid",
        ),
        migrations.AlterField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(related_name="orders", to="vendor.vendor"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="vendor.vendor",
            ),
        ),
    ]
