# Generated by Django 5.0.1 on 2024-03-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_rename_paid_ammount_order_paid_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(default=1, max_length=50),
        ),
    ]
